project:
  type: website

website:
  title: "Karat Sidhu"
  site-url: https://karatsidhu.com
  repo-url: https://github.com/sidhuk/karat_codes
  google-analytics: "G-ZVPYZZSZ1B"
  repo-actions: [edit, issue]
  comments:
    utterances:
      repo: sidhuk/karat_codes
      label: "Comments"
      theme: github-light
  open-graph: true
  favicon: data/images/logo.png
  twitter-card:
    creator: "@karat_sidhu"
    card-style: summary_large_image
  navbar:
    right:
      - text: "About"
        href: data/about/about.qmd
      - text: Resumé
        href: data/pdf/cv.pdf
      - text: "Posts"
        menu:
          - href: blog.qmd
            text: Today I Learned
          - href: data/gallery/index.qmd
            text: Gallery
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/karat_sidhu
  page-footer:
    left: "© 2022 Karat Sidhu"
    right: |
      Made with ♥ using `{Quarto}`
    center: |
      <a href="https://www.linkedin.com/in/karatsidhu/"><i class="fa-brands fa-linkedin-in"></i></a>
      <a href ="https://karatsidhu.com/data/pdf/cv.pdf"><i class="fa-solid fa-book-bookmark"></i></a>
      <a href="https://www.twitter.com/karat_sidhu/"><i class="fa-brands fa-twitter"></i></a>
      <a href="mailto:karatsingh@gmail.com"><i class="fa-solid fa-at"></i></a>
      <a href="https://orcid.org/0000-0002-8769-0926"><i class="fa-brands fa-orcid"></i></a>
      <a href="https://github.com/SidhuK"><i class="fa-brands fa-github"></i></a>
      <a href="https://www.researchgate.net/profile/Karatatiwant-Sidhu"><i class="fa-brands fa-researchgate"></i></a>
      <center>
citation: true
license: "CC BY"
format:
  html:
    theme:
      light: css/karat_quarto.scss
    css: css/karat.css
    include-after-body: footer.html
freeze: true
